services:
  games:
    command: ["bun", "run", "dev"]
    volumes:
      - ./services/games/src:/app/services/games/src
      - ./packages:/app/packages

  wallets:
    command: ["bun", "run", "dev"]
    volumes:
      - ./services/wallets/src:/app/services/wallets/src
      - ./packages:/app/packages

  frontend:
    command: ["bun", "run", "dev", "--host", "0.0.0.0", "--port", "80"]
    environment:
      - VITE_PROXY_TARGET=http://kong:8000
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/index.html:/app/frontend/index.html
      - ./frontend/vite.config.ts:/app/frontend/vite.config.ts
      - ./frontend/tsconfig.json:/app/frontend/tsconfig.json
