services:
  kong:
    environment:
      KONG_DECLARATIVE_CONFIG: /kong/kong.prod.yml

  games:
    command: ["bun", "run", "src/main.ts"]
    volumes: !reset [] 
    ports: !reset [] 

  wallets:
    command: ["bun", "run", "src/main.ts"]
    volumes: !reset [] 
    ports: !reset [] 

  frontend:
    command: ["bun", "run", "preview", "--", "--port", "80", "--host"]
    volumes: !reset [] 
